(() => {
'use strict';
const raids={hyjal:{name:'Hyjal Summit',size:20,mark:'HY'},barrow:{name:'Barrow Deeps',size:10,mark:'BD'},onyxia:{name:'Onyxias Hort',size:40,mark:'ON'}};
const labels={tank:'Tank',heal:'Heiler',dd:'Schaden',signed:'Zugesagt',bench:'Ersatzbank',late:'Später',tentative:'Vielleicht',absent:'Abgesagt',open:'Anmeldung offen',closed:'Anmeldung geschlossen',cancelled:'Abgesagt',completed:'Abgeschlossen',warrior:'Krieger',paladin:'Paladin',hunter:'Jäger',rogue:'Schurke',priest:'Priester',shaman:'Schamane',mage:'Magier',warlock:'Hexenmeister',druid:'Druide'};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(text,fn,cls='quiet')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
function link(kind,id){const u=new URL(location.href);u.hash='prioseiten';u.searchParams.set('loot',kind);u.searchParams.delete('raid');if(id)u.searchParams.set('raid',id);return u.pathname+u.search+u.hash;}
function navigate(kind,id){history.pushState(null,'',link(kind,id));dispatchEvent(new Event('hashchange'));}
function select(label,name,options,value){const wrap=el('label',label),input=el('select');input.name=name;for(const [v,t] of options)input.add(new Option(t,v));input.value=value;wrap.append(input);return {wrap,input};}
document.querySelectorAll('[data-forever-prio]').forEach(a=>{a.href=link(a.dataset.foreverPrio);a.onclick=e=>{if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(a.dataset.foreverPrio);};});
window.renderForeverPrios=host=>{
 host.classList.add('forever-prios-view');host.replaceChildren();
 const state=window.foreverPlanning?.data,query=new URLSearchParams(location.search),requested=query.get('raid'),requestedRaid=state?.raids.find(r=>r.id===requested);
 const kind=raids[query.get('loot')]?query.get('loot'):raids[requestedRaid?.kind]?requestedRaid.kind:'hyjal',config=raids[kind];
 document.querySelectorAll('[data-forever-prio]').forEach(a=>{const selected=a.dataset.foreverPrio===kind;a.classList.toggle('selected',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 const events=(state?.raids||[]).filter(r=>r.kind===kind),raid=events.find(r=>r.id===requested)||(!requested?events.find(r=>new Date(r.starts_at)>new Date()&&r.status==='open')||events[0]:null);
 const header=el('header',undefined,'prio-heading'),intro=el('div');intro.append(el('span','GUILDLOOT · FOREVER','eyebrow'),el('h1',config.name+' · Loot & Anmeldung'),el('p',state?state.guild.name+' · Eure Termine, Teilnehmer und Prioritäten.':'Wähle deinen Raid und melde dich mit deinem Forever-SpielerLogin an.','subtle'));header.append(intro);host.append(header);
 const tabs=el('nav',undefined,'prio-raid-tabs');tabs.setAttribute('aria-label','Forever-Lootseiten');for(const [k,r] of Object.entries(raids)){const a=el('a',undefined,k===kind?'active':'');a.href=link(k);if(k===kind)a.setAttribute('aria-current','page');a.append(el('span',r.mark,'prio-raid-mark'));const text=el('span');text.append(el('strong',r.name),el('small',r.size+' Spieler'));a.append(text);a.onclick=e=>{if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(k);};tabs.append(a);}host.append(tabs);
 const calendar=el('section',undefined,'panel prio-event');const eventHead=el('div',undefined,'section-title');eventHead.append(el('h2','Euer Raidtermin'));if(state?.actor.canManage)eventHead.append(button('Termin erstellen',()=>window.foreverPlanning.createRaid(kind),'primary'));calendar.append(eventHead);
 if(events.length){const picker=select('Termin auswählen','raid',events.map(r=>[r.id,new Date(r.starts_at).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'})+' · '+r.title]),raid?.id||'');if(!raid)picker.input.prepend(new Option('Verlinkten Termin nicht in dieser Ansicht gefunden','',true,true));picker.input.onchange=()=>navigate(kind,picker.input.value);calendar.append(picker.wrap);}else calendar.append(el('p',state?'Für '+config.name+' ist noch kein Termin in dieser Ansicht vorhanden.':'Melde dich an, um die Termine deiner Gilde zu sehen.','subtle'));
 if(requested&&!raid)calendar.append(el('p','Der verlinkte Termin ist hier nicht verfügbar. Prüfe die Gilde oder öffne die Raidchronik für vergangene Termine.','subtle'));
 if(raid){const detail=el('div',undefined,'prio-event-detail');detail.append(el('span',labels[raid.status],'tag'),el('span',raid.size+' Plätze · '+(raid.group_name||'Gildenweiter Termin'),'subtle'));calendar.append(detail);if(raid.description)calendar.append(el('p',raid.description,'description'));}
 const registration=el('div',undefined,'prio-registration');registration.append(el('h3','Deine Raidanmeldung'));
 if(!state){const a=el('a','Mit Forever-SpielerLogin anmelden','primary'),u=new URL('forever-start.html',location.href);if(query.get('guild'))u.searchParams.set('guild',query.get('guild'));a.href=u.pathname+u.search;registration.append(el('p','Deine Anmeldung gehört zu einem konkreten Termin deiner Gilde.','subtle'),a);}
 else if(!raid)registration.append(el('p','Sobald eure Leitung einen Termin anlegt, kannst du hier deinen Charakter und deine Teilnahme auswählen.','subtle'));
 else if(!state.actor.canSignup)registration.append(el('p','Du bist als Gildenleitung angemeldet. Für eine eigene Teilnahme verwende deinen Forever-SpielerLogin.','subtle'));
 else if(!state.characters.length)registration.append(button('Forever-Charakter anlegen',()=>window.foreverPlanning.createCharacter(),'primary'));
 else {const mine=raid.signups.find(s=>s.mine),c=state.characters.find(c=>c.id===mine?.characterId)||state.characters[0];if(mine)registration.append(el('p',labels[mine.status]+' · '+mine.name,'my-status'));
  if(raid.status!=='open'||new Date(raid.starts_at)<=new Date())registration.append(el('p','Die Anmeldung für diesen Termin ist geschlossen.','subtle'));
  else {const form=el('form',undefined,'prio-signup-form'),char=select('Dein Charakter','characterId',state.characters.map(c=>[c.id,c.name+' · '+labels[c.class_name]]),c.id),role=select('Rolle','role',['tank','heal','dd'].map(k=>[k,labels[k]]),mine?.role||c.role),status=select('Teilnahme','status',['signed','bench','late','tentative','absent'].map(k=>[k,labels[k]]),mine?.status||'signed');char.input.onchange=()=>{role.input.value=state.characters.find(c=>c.id===char.input.value).role;};const noteLabel=el('label','Hinweis (optional)'),note=el('input');note.name='note';note.maxLength=240;note.value=mine?.note||'';note.placeholder='Zum Beispiel: ab 20:30 Uhr';noteLabel.append(note);const submit=el('button',mine?'Anmeldung speichern':'Zum Raid anmelden','primary');submit.type='submit';const message=el('p','','form-error');message.setAttribute('role','status');form.append(char.wrap,role.wrap,status.wrap,noteLabel,submit,message);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;message.textContent='Wird gespeichert …';try{const result=await window.foreverPlanning.signup(raid.id,Object.fromEntries(new FormData(form)));const done=el('p',result.status==='bench'?'Der Termin ist voll. Du stehst auf der Ersatzbank.':'Deine Anmeldung wurde gespeichert.','my-status');done.setAttribute('role','status');host.querySelector('.prio-registration')?.prepend(done);}catch(error){message.textContent=error.message;submit.disabled=false;}};registration.append(form);}
 }
 calendar.append(registration);host.append(calendar);
 const grid=el('div',undefined,'prio-columns'),loot=el('section',undefined,'panel'),priorities=el('section',undefined,'panel');loot.append(el('span','GEGENSTÄNDE & DROPQUELLEN','eyebrow'),el('h2','Möglicher Loot'));const search=el('input');search.type='search';search.placeholder='Item, Boss oder Kategorie suchen …';search.disabled=true;search.setAttribute('aria-label','Loot durchsuchen – nach Ergänzung der Lootliste verfügbar');const cls=select('Klasse','class',[['','Alle Klassen'],...Object.keys(labels).filter(k=>['warrior','paladin','hunter','rogue','priest','shaman','mage','warlock','druid'].includes(k)).map(k=>[k,labels[k]])],'');cls.input.disabled=true;loot.append(search,cls.wrap);const empty=el('div',undefined,'prio-loot-empty');empty.append(el('span','◇','prio-empty-icon'),el('h3','Lootliste wird ergänzt'),el('p','Für '+config.name+' ist noch keine bestätigte Forever-Lootliste hinterlegt. Sobald die Gegenstände und Dropquellen vorliegen, erscheint hier die Auswahl für P1, P2 und P3.'));const discover=el('a','Vorhandene Items entdecken →');discover.href='#itemdatenbank';empty.append(discover);loot.append(empty);
 priorities.append(el('span','EURE PRIORITÄTEN','eyebrow'),el('h2','Aktuelle Prioliste'));const selection=el('div',undefined,'prio-selection');selection.append(el('h3','Deine Auswahl'));for(const p of ['P1','P2','P3']){const row=el('div',undefined,'prio-slot');row.append(el('strong',p),el('span','Noch kein Item gewählt'));selection.append(row);}selection.append(el('p','Die Raidanmeldung ist bereits nutzbar. Die Prio-Auswahl wird nach Ergänzung der Lootliste freigeschaltet.','subtle'));priorities.append(selection);const save=button('Prios speichern · noch nicht verfügbar',()=>{},'primary');save.disabled=true;priorities.append(save);const find=el('input');find.type='search';find.placeholder='Anmeldungen nach Spieler oder Klasse durchsuchen …';find.setAttribute('aria-label','Anmeldungen durchsuchen');priorities.append(find);const tableWrap=el('div',undefined,'prio-table-wrap');tableWrap.tabIndex=0;tableWrap.setAttribute('role','region');tableWrap.setAttribute('aria-label','Anmeldungen und Prioliste');const table=el('table'),head=el('thead'),tr=el('tr');for(const title of ['Spieler / Klasse','Teilnahme','P1','P2','P3','P0 / P0+']){const th=el('th',title);th.scope='col';tr.append(th);}head.append(tr);const body=el('tbody');table.append(head,body);tableWrap.append(table);priorities.append(tableWrap,el('p','P0/P0+ ist für Forever noch nicht aktiv. „—“ bedeutet: keine Prio hinterlegt.','subtle'));const draw=()=>{body.replaceChildren();const q=find.value.trim().toLocaleLowerCase('de'),rows=(raid?.signups||[]).filter(s=>(s.name+' '+(labels[s.className]||'')).toLocaleLowerCase('de').includes(q));for(const s of rows){const row=el('tr'),who=el('td'),identity=el('div'),info=el('div');info.append(el('strong',s.name+(s.mine?' · Du':'')),el('small',labels[s.className]+' · '+labels[s.role]));window.foreverClassIdentity(identity,info,s.className);who.append(identity);row.append(who,el('td',labels[s.status]));for(let i=0;i<4;i++)row.append(el('td','—'));body.append(row);}if(!rows.length){const row=el('tr'),td=el('td',!raid?'Wähle einen Raidtermin, um die Anmeldungen zu sehen.':q?'Keine passenden Anmeldungen.':'Für diesen Termin gibt es noch keine Anmeldungen.');td.colSpan=6;row.append(td);body.append(row);}};find.oninput=draw;draw();grid.append(loot,priorities);host.append(grid);
 if(raid){const footer=el('div',undefined,'prio-footer');const signed=raid.signups.filter(s=>s.status==='signed').length;footer.append(el('p',signed+' / '+raid.size+' Plätze belegt · '+raid.signups.filter(s=>s.status==='bench').length+' auf Ersatzbank','subtle'),button('Teilnehmer & Rollen ansehen',()=>window.foreverPlanning.roster(raid.id)),button('Aktualisieren',async()=>{try{await window.foreverPlanning.refresh();}catch(e){footer.append(el('p',e.message,'form-error'));}}));host.append(footer);}
};
})();
