(function(root){
'use strict';
const ordered=t=>[...t.talents].sort((a,b)=>a.row-b.row||a.col-b.col);
const count=(t,r)=>t.talents.reduce((n,x)=>n+(r[x.id]||0),0);
const total=(c,r)=>c.trees.reduce((n,t)=>n+count(t,r),0);
function valid(c,r){if(total(c,r)>51)return false;return c.trees.every(t=>t.talents.every(x=>{const v=r[x.id]||0;if(!Number.isInteger(v)||v<0||v>x.maxRank)return false;if(!v)return true;const lower=t.talents.filter(a=>a.row<x.row).reduce((n,a)=>n+(r[a.id]||0),0);return lower>=x.row*5&&x.requires.every(d=>{const parent=t.talents.find(a=>a.id===d.id);return !parent||(r[d.id]||0)>=Math.min(d.qty,parent.maxRank);});}));}
function change(c,r,x,delta){const next={...r,[x.id]:(r[x.id]||0)+delta};return valid(c,next)?next:r;}
const encode=(c,r)=>c.trees.map(t=>ordered(t).map(x=>r[x.id]||0).join('').replace(/0+$/,'')).join('-').replace(/-+$/,'');
function decode(c,code){if(!/^[0-5]*(?:-[0-5]*){0,2}$/.test(code))throw Error('Ungültiger Build-Code.');const parts=code.split('-'),r={};c.trees.forEach((t,i)=>{const chars=parts[i]||'',ts=ordered(t);if(chars.length>ts.length)throw Error('Der Build passt nicht zu dieser Klasse.');ts.forEach((x,j)=>r[x.id]=Number(chars[j]||0));});if(!valid(c,r))throw Error('Der Build verletzt die Punkte- oder Talentvoraussetzungen.');return r;}
root.ForeverTalentEngine={valid,change,encode,decode,total,count};
if(typeof document==='undefined')return;
const el=id=>document.getElementById(id),names={warrior:'Krieger',paladin:'Paladin',hunter:'Jäger',rogue:'Schurke',priest:'Priester',shaman:'Schamane',mage:'Magier',warlock:'Hexenmeister',druid:'Druide'},flags={new:'★ Neu',changed:'◆ Geändert',unchanged:'✓ Classic bestätigt',classic:'? Noch nicht bestätigt'};
let data,cls,ranks={},selected=null,loading=false;const sessions={};
function node(tag,text,attrs={}){const n=document.createElement(tag);if(text)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function message(s){el('talentMessage').textContent=s;}
function url(){const u=new URL(location.href);u.hash='talente';u.searchParams.set('talentClass',cls.slug);u.searchParams.set('build',encode(cls,ranks));return u.href;}
function sync(){sessions[cls.slug]={...ranks};history.replaceState(null,'',url());}
let tip=null,tipAnchor=null,tipTimer=null,tipOpen=false;
function closeTip(){clearTimeout(tipTimer);tipOpen=false;if(tip)tip.hidden=true;document.querySelectorAll('.talent-node[aria-expanded="true"]').forEach(b=>b.setAttribute('aria-expanded','false'));}
function delayClose(){clearTimeout(tipTimer);tipTimer=setTimeout(closeTip,180);}
function placeTip(){if(!tip||!tipOpen||!tipAnchor)return;const margin=12,rect=tipAnchor.getBoundingClientRect();tip.style.maxHeight=(innerHeight-margin*2)+'px';const width=tip.offsetWidth,height=tip.offsetHeight;let left=rect.right+14;if(left+width>innerWidth-margin)left=rect.left-width-14;left=Math.max(margin,Math.min(left,innerWidth-width-margin));const top=innerWidth<=760?innerHeight-height-margin:Math.max(margin,Math.min(rect.top-12,innerHeight-height-margin));tip.style.left=left+'px';tip.style.top=top+'px';}
function updateTip(){if(!tipOpen||!selected)return;clearTimeout(tipTimer);if(!tip){tip=node('aside','',{id:'talentTooltip',class:'talent-tooltip',role:'dialog','aria-label':'Talentkarte'});tip.hidden=true;tip.onmouseenter=()=>clearTimeout(tipTimer);tip.onmouseleave=delayClose;tip.onfocusin=()=>clearTimeout(tipTimer);tip.onfocusout=e=>{if(!tip.contains(e.relatedTarget))delayClose();};document.body.append(tip);}
 tip.replaceChildren();const {talent:x,tree:t}=selected;const header=node('div','',{class:'talent-tooltip-head'}),img=node('img','',{src:`https://wow.zamimg.com/images/wow/icons/large/${encodeURIComponent(x.icon)}.jpg`,alt:''}),title=node('div');title.append(node('span',t.name,{class:'talent-tooltip-tree'}),node('h3',x.name),node('span',`Rang ${ranks[x.id]||0} / ${x.maxRank}`,{class:'talent-tooltip-rank'}));const close=node('button','×',{type:'button',class:'talent-tooltip-close','aria-label':'Talentkarte schließen'});close.onclick=()=>{closeTip();tipAnchor?.focus({preventScroll:true});closeTip();};header.append(img,title,close);tip.append(header);
 const body=node('div','',{class:'talent-tooltip-body'});const source=el('talentDetails');for(const n of source.children){if(n.tagName==='H3')continue;body.append(n.cloneNode(true));}body.querySelectorAll('.talent-detail-actions button').forEach((b,i)=>{b.onclick=()=>adjust(x,i?1:-1);});tip.append(body);tip.hidden=false;tipAnchor=document.querySelector(`[data-talent-id="${x.id}"]`)||tipAnchor;tipAnchor?.setAttribute('aria-expanded','true');placeTip();}
function openTip(x,t,anchor){clearTimeout(tipTimer);selected={talent:x,tree:t};tipAnchor=anchor;tipOpen=true;inspect();}
addEventListener('resize',placeTip);addEventListener('scroll',e=>{if(tipOpen&&!tip?.contains(e.target))placeTip();},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTip();});document.addEventListener('pointerdown',e=>{if(tipOpen&&!tip?.contains(e.target)&&!e.target.closest('.talent-node'))closeTip();});addEventListener('forever-panel',e=>{if(e.detail!=='talente')closeTip();});
function inspect(){const box=el('talentDetails');box.replaceChildren();if(!selected){box.append(node('p','Wähle ein Talent für die Beschreibung. Linksklick: +1 · Rechtsklick: −1 · Umschalt-Klick: auffüllen.'));return;}
 const {talent:x,tree:t}=selected,v=ranks[x.id]||0;box.append(node('h3',x.name),node('p',`${t.name} · Rang ${v}/${x.maxRank} · ${flags[x.status]||'Datenstand offen'}`));
 if(x.cost)box.append(node('p',x.cost));
 if(v){box.append(node('h4','Aktueller Rang'),node('p',x.ranks[v-1]?.description||'Für diesen Rang liegt noch kein bestätigter Text vor.'));}
 if(v<x.maxRank)box.append(node('h4','Nächster Rang'),node('p',x.ranks[v]?.description||'Für diesen Rang liegt noch kein bestätigter Text vor.'));
 const requirements=x.requires.map(d=>`${Math.min(d.qty,t.talents.find(a=>a.id===d.id)?.maxRank||d.qty)} Punkte in ${t.talents.find(a=>a.id===d.id)?.name||'Vorgängertalent'}`);box.append(node('p',`Voraussetzung: ${x.row*5} Punkte in früheren Reihen${requirements.length?' · '+requirements.join(' · '):''}`));
 const actions=node('div','',{class:'talent-detail-actions'});for(const[caption,delta]of [['− Punkt',-1],['+ Punkt',1]]){const b=node('button',caption,{type:'button'});b.disabled=change(cls,ranks,x,delta)===ranks;b.onclick=()=>adjust(x,delta);actions.append(b);}box.append(actions);
 if(el('talentClassic').checked&&x.classic){const d=node('details'),sum=node('summary','Classic-Vergleich');d.append(sum);x.classic.ranks.forEach((r,i)=>d.append(node('p',`Rang ${i+1}: ${r.description}`)));box.append(d);}
 updateTip();
}
function adjust(x,d,fill=false){let next=change(cls,ranks,x,d);if(next===ranks){message(d>0?'Punkt nicht möglich: Maximum oder Voraussetzungen prüfen.':'Dieser Punkt wird noch für andere Talente benötigt.');return;}if(fill)while(true){const more=change(cls,next,x,1);if(more===next)break;next=more;}const focusId=document.activeElement?.dataset?.talentId;ranks=next;sync();render();if(focusId)document.querySelector(`[data-talent-id="${focusId}"]`)?.focus({preventScroll:true});message('Build aktualisiert.');}
function render(){el('talentPoints').textContent=`${51-total(cls,ranks)} Punkte frei · Stufe ${total(cls,ranks)?total(cls,ranks)+9:1} · ${cls.trees.map(t=>count(t,ranks)).join(' / ')}`;el('talentClasses').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.class===cls.slug)));el('talentShare').value=url();el('talentOriginal').href=`https://wowforevertalents.com/${cls.slug}/?t=${encode(cls,ranks)}`;
 const host=el('talentTrees');host.replaceChildren();cls.trees.forEach(t=>{const section=node('section','',{class:'talent-tree'}),head=node('div','',{class:'talent-tree-head'});head.append(node('h3',`${t.name} · ${count(t,ranks)}`));const reset=node('button','Zurücksetzen',{type:'button'});reset.onclick=()=>{for(const x of t.talents)delete ranks[x.id];sync();render();message('Baum zurückgesetzt.');};head.append(reset);section.append(head);
 const grid=node('div','',{class:'talent-nodes'});grid.style.setProperty('--rows',Math.max(7,...t.talents.map(x=>x.row+1)));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 400 '+Math.max(7,...t.talents.map(x=>x.row+1))*100);svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.classList.add('talent-arrows');
 for(const x of t.talents)for(const req of x.requires){const a=t.talents.find(v=>v.id===req.id);if(!a)continue;const path=document.createElementNS(svg.namespaceURI,'path');const ax=a.col*100+50,ay=a.row*100+45,bx=x.col*100+50,by=x.row*100+45;path.setAttribute('d',`M ${ax} ${ay} V ${(ay+by)/2} H ${bx} V ${by}`);svg.append(path);}grid.append(svg);
 for(const x of ordered(t)){const v=ranks[x.id]||0,b=node('button','',{type:'button',class:'talent-node '+(v===x.maxRank?'maxed':v?'chosen':change(cls,ranks,x,1)===ranks?'locked':''),'aria-label':`${x.name}, Rang ${v} von ${x.maxRank}`,'aria-describedby':'talentHelp','data-talent-id':String(x.id),'aria-haspopup':'dialog','aria-controls':'talentTooltip','aria-expanded':'false'});b.style.gridRow=x.row+1;b.style.gridColumn=x.col+1;const img=node('img','',{src:`https://wow.zamimg.com/images/wow/icons/large/${encodeURIComponent(x.icon)}.jpg`,alt:'',loading:'lazy'});b.append(img,node('span',`${v}/${x.maxRank}`),node('small',x.status==='new'?'★':x.status==='changed'?'◆':x.status==='classic'?'?':''));b.onpointerdown=e=>{b.dataset.pointer=e.pointerType;};b.onmouseenter=()=>openTip(x,t,b);b.onmouseleave=delayClose;b.onfocus=()=>openTip(x,t,b);b.onblur=e=>{if(!tip?.contains(e.relatedTarget))delayClose();};b.onclick=e=>{openTip(x,t,b);if(b.dataset.pointer!=='touch')adjust(x,1,e.shiftKey);};b.oncontextmenu=e=>{e.preventDefault();openTip(x,t,b);adjust(x,-1);};b.onkeydown=e=>{if(['-','Backspace','Delete'].includes(e.key)){e.preventDefault();openTip(x,t,b);adjust(x,-1);}if(e.key==='Escape')closeTip();};grid.append(b);}section.append(grid);host.append(section);});inspect();}
function choose(slug,code){closeTip();cls=data.classes.find(c=>c.slug===slug)||data.classes[0];selected=null;ranks=code===undefined?(sessions[cls.slug]||{}):decode(cls,code);sync();render();}
function readSaved(){try{return JSON.parse(localStorage.getItem('guildloot_forever_builds')||'[]');}catch{return [];}}
function savedOptions(){const select=el('talentSaved');select.replaceChildren(node('option','Gespeicherten Build wählen',{value:''}));readSaved().forEach((b,i)=>select.append(node('option',`${b.name} · ${names[b.cls]}`,{value:String(i)})));}
async function start(){if(data||loading||!el('talentTrees'))return;loading=true;try{const res=await fetch('forever-talents-data.json?v=20260914');if(!res.ok)throw Error('Talentdaten konnten nicht geladen werden.');data=await res.json();for(const c of data.classes){const b=node('button','',{type:'button',class:'talent-class-card','data-class':c.slug,'aria-pressed':'false'});b.style.setProperty('--class-color',c.color);b.append(node('img','',{src:`https://wow.zamimg.com/images/wow/icons/large/${encodeURIComponent(c.icon)}.jpg`,alt:''}),node('span',names[c.slug]||c.name));b.onclick=()=>choose(c.slug);el('talentClasses').append(b);}
 el('talentClassic').onchange=inspect;el('talentReset').onclick=()=>{ranks={};sync();render();message('Alle Punkte zurückgesetzt.');};
 el('talentCopy').onclick=async()=>{try{await navigator.clipboard.writeText(url());message('Build-Link kopiert.');}catch{el('talentShare').focus();el('talentShare').select();message('Bitte den markierten Link kopieren.');}};
 el('talentImportButton').onclick=()=>{try{let input=el('talentImport').value.trim(),slug=cls.slug,code=input;if(input.includes('://')){const u=new URL(input);slug=u.searchParams.get('talentClass')||u.pathname.split('/').filter(Boolean)[0];code=u.searchParams.get('build')??u.searchParams.get('t')??'';}const c=data.classes.find(c=>c.slug===slug);if(!c)throw Error('Klasse nicht erkannt.');decode(c,code);choose(slug,code);message('Build importiert.');}catch(e){message(e.message);}};
 el('talentSave').onclick=()=>{const name=el('talentName').value.trim();if(!name){message('Bitte einen Namen für den Build eingeben.');return;}try{const all=readSaved();all.push({name:name.slice(0,80),cls:cls.slug,code:encode(cls,ranks)});localStorage.setItem('guildloot_forever_builds',JSON.stringify(all.slice(-30)));savedOptions();message('Build in diesem Browser gespeichert.');}catch{message('Speichern im Browser ist nicht verfügbar. Bitte den Build-Link sichern.');}};
 el('talentSaved').onchange=e=>{if(e.target.value==='')return;try{const b=readSaved()[Number(e.target.value)];choose(b.cls,b.code);el('talentName').value=b.name;message('Gespeicherten Build geladen.');}catch(error){message(error.message);}};
 const q=new URLSearchParams(location.search);const slug=q.get('talentClass')||'shaman',code=q.get('build')??'05003305201-050032131005112251';try{choose(slug,code);}catch(e){choose(slug,'');message(e.message);}savedOptions();el('talentLoading').hidden=true;
 }catch(e){message(e.message+' Bitte die Seite neu laden.');data=null;}finally{loading=false;}}
root.startForeverTalents=start;if(location.hash==='#talente')start();addEventListener('forever-panel',e=>{if(e.detail==='talente')start();});
})(typeof window==='undefined'?globalThis:window);
