import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createDkpService,dkpAmount,lootSystem} from '../src/dkp.js';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create table guilds(id uuid primary key);create table guild_settings(guild_id uuid primary key,layout_json jsonb,updated_at timestamptz default now());
create table players(id uuid primary key,guild_id uuid,player_pin text);create table characters(id uuid primary key,player_id uuid,name text,server text,class_name text);`);
const g={id:randomUUID()},g2={id:randomUUID()},p=randomUUID(),p2=randomUUID(),foreign=randomUUID(),c=randomUUID(),c2=randomUUID(),other=randomUUID();
for(const guild of [g,g2]){await db.query('insert into guilds values($1)',[guild.id]);await db.query("insert into guild_settings(guild_id,layout_json) values($1,'{\"lootSystem\":\"prio\",\"keep\":1}')",[guild.id]);}
for(const [id,gid,pin] of [[p,g.id,'PLAYER'],[p2,g.id,'SECOND'],[foreign,g2.id,'FOREIGN']])await db.query('insert into players values($1,$2,$3)',[id,gid,pin]);
for(const [id,pid,name] of [[c,p,'Ariee'],[c2,p2,'Zweiter'],[other,foreign,'Fremd']])await db.query("insert into characters values($1,$2,$3,'Anderer Realm','Magier')",[id,pid,name]);
const auth=(guild,params)=>{if(params.masterCode!==`MASTER-${guild.id}`)throw Object.assign(Error('Forbidden'),{statusCode:403});};
// PGlite has one connection. A queue preserves PostgreSQL transaction boundaries for the tests.
let tail=Promise.resolve();
const pool={async connect(){let release;const before=tail;tail=new Promise(resolve=>release=resolve);await before;return {query:(s,a)=>db.query(s,a),release};}};
const service=createDkpService({pool,query:(s,a)=>a?db.query(s,a):db.exec(s),authorize:auth,authorizeMode:auth});
await service.ensure();await service.ensure();
let checks=0;
const check=(a,b)=>{assert.deepEqual(a,b);checks++;};
const manager={masterCode:`MASTER-${g.id}`};
const write=(payload,creds=manager,guild=g)=>service.change(guild,{...creds,requestId:randomUUID(),...payload});
const state=(creds={playerPin:'PLAYER'},guild=g)=>service.state(guild,creds);
const rejects=async(fn,status)=>{await assert.rejects(fn,e=>e.statusCode===status);checks++;};
check(lootSystem(),'prio');check(dkpAmount('12,50'),'12.50');
for(const n of ['0','-1','NaN','Infinity','1.001','1e3','100000000']){assert.throws(()=>dkpAmount(n));checks++;}
await rejects(()=>state({playerPin:'FOREIGN'}),403);
await rejects(()=>write({action:'book',characterIds:[c],amount:10,kind:'credit',reason:'Raid'}),409);
await write({action:'setMode',lootSystem:'dkp'});
check((await db.query('select layout_json from guild_settings where guild_id=$1',[g.id])).rows[0].layout_json.keep,1);
await rejects(()=>write({action:'setMode',lootSystem:'invalid'}),400);
const book={action:'book',requestId:randomUUID(),characterIds:[c,c2],amount:'100',kind:'credit',reason:'Raidteilnahme',raid:'MC'};
await write(book);check((await state()).accounts.find(a=>a.id===c).balance,100);
check((await write(book)).replayed,true);check((await state()).ledger.length,2);
await rejects(()=>write({...book,amount:200}),409);
await rejects(()=>write({action:'book',characterIds:[c,other],amount:10,kind:'credit',reason:'Falsche Gilde'}),403);
check((await state()).accounts.find(a=>a.id===c).balance,100);
await rejects(()=>write({action:'book',characterIds:[c],amount:1,kind:'credit',reason:'Hack'},{playerPin:'PLAYER'}),403);
await rejects(()=>write({action:'book',characterIds:[c],amount:1,kind:'loot',reason:'Loot ohne Item'}),400);
await write({action:'book',characterIds:[c],amount:10,kind:'loot',reason:'Loot',item:'Klinge'});
check((await state()).accounts.find(a=>a.id===c).balance,90);
const a=(await write({action:'openAuction',item:'Item A',amount:5})).auctionId;
const b=(await write({action:'openAuction',item:'Item B',amount:5})).auctionId;
await rejects(()=>write({action:'bid',auctionId:a,characterId:c2,amount:10},{playerPin:'PLAYER'}),403);
await write({action:'bid',auctionId:a,characterId:c,amount:60},{playerPin:'PLAYER'});
check((await state()).accounts.find(a=>a.id===c).reserved,60);
await rejects(()=>write({action:'bid',auctionId:b,characterId:c,amount:40},{playerPin:'PLAYER'}),409);
await rejects(()=>write({action:'book',characterIds:[c],amount:40,kind:'loot',reason:'Ausgabe',item:'Item'}),409);
await rejects(()=>write({action:'setMode',lootSystem:'prio'}),409);
await write({action:'bid',auctionId:a,characterId:c,amount:70},{playerPin:'PLAYER'});
await rejects(()=>write({action:'bid',auctionId:a,characterId:c2,amount:70},{playerPin:'SECOND'}),409);
await write({action:'bid',auctionId:a,characterId:c2,amount:75},{playerPin:'SECOND'});
check((await state()).accounts.find(a=>a.id===c).reserved,0);
const close={action:'closeAuction',auctionId:a,requestId:randomUUID()};
await rejects(()=>write(close,{playerPin:'PLAYER'}),403);
await write(close);await write(close);
check((await state()).accounts.find(a=>a.id===c2).balance,25);
check((await state()).ledger.filter(e=>e.kind==='auction').length,1);
await rejects(()=>write({action:'closeAuction',auctionId:a}),409);
await rejects(()=>write({action:'bid',auctionId:a,characterId:c,amount:80},{playerPin:'PLAYER'}),409);
await write({action:'bid',auctionId:b,characterId:c,amount:20},{playerPin:'PLAYER'});
await write({action:'cancelAuction',auctionId:b});
check((await state()).accounts.find(a=>a.id===c).reserved,0);
check((await state()).accounts.find(a=>a.id===c).balance,90);
const empty=(await write({action:'openAuction',item:'Kein Gebot',amount:1})).auctionId;
await write({action:'closeAuction',auctionId:empty});
await write({action:'setMode',lootSystem:'prio'});
check((await state()).lootSystem,'prio');check((await state()).accounts.find(a=>a.id===c2).balance,25);
check((await state({playerPin:'FOREIGN'},g2)).ledger.length,0);
await service.assertPrio(g.id);await write({action:'setMode',lootSystem:'dkp'});await rejects(()=>service.assertPrio(g.id),409);
// Two simultaneous requests using the same key must settle only once.
const double={action:'book',requestId:randomUUID(),characterIds:[c],amount:1,kind:'credit',reason:'Doppelklick'};
await Promise.all([write(double),write(double)]);check((await state()).accounts.find(a=>a.id===c).balance,91);
const setBalance={action:'setBalance',characterId:c,amount:42,expectedBalance:91,reason:'Punktestand korrigiert',requestId:randomUUID()};
await write(setBalance);check((await state()).accounts.find(a=>a.id===c).balance,42);await write(setBalance);check((await state()).accounts.find(a=>a.id===c).balance,42);
await rejects(()=>write({...setBalance,requestId:randomUUID(),amount:20}),409);
await rejects(()=>write({...setBalance,requestId:randomUUID(),expectedBalance:42,amount:-1}),400);
await write({...setBalance,requestId:randomUUID(),expectedBalance:42,amount:0});check((await state()).accounts.find(a=>a.id===c).balance,0);
await rejects(()=>write({...setBalance,requestId:randomUUID(),expectedBalance:0,amount:20},{playerPin:'PLAYER'}),403);
const reserved=(await write({action:'openAuction',item:'Reserviert',amount:1})).auctionId;
await write({action:'bid',auctionId:reserved,characterId:c2,amount:20},{playerPin:'SECOND'});
await rejects(()=>write({action:'setBalance',characterId:c2,amount:10,expectedBalance:25,reason:'Darf Gebot nicht unterschreiten'}),409);
await write({action:'cancelAuction',auctionId:reserved});
await db.close();console.log(`${checks} DKP checks passed: PostgreSQL transactions, authorization, guild isolation, reservations, settlement, retries and mode changes.`);
