import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createForeverRaids,foreverSchema} from '../src/forever-raids.js';
import {createForeverAccess,foreverQuery} from '../src/forever-db.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE||'@electric-sql/pglite');
const db=new PGlite();await db.exec(await readFile(new URL('../src/forever-core.sql',import.meta.url),'utf8'));await db.exec(foreverSchema);await db.exec(await readFile(new URL('../src/forever-loot.sql',import.meta.url),'utf8'));
const query=(s,p=[])=>p.length?db.query(s,p):db.exec(s).then(r=>r.at(-1));const pool={connect:async()=>({query,release(){}})};
const guild={id:randomUUID(),slug:'forever',name:'Lichtbringer'},other={id:randomUUID(),slug:'other',name:'Andere'},player=randomUUID(),foreign=randomUUID();
for(const g of [guild,other]){await query('insert into guilds(id,slug,name) values($1,$2,$3)',[g.id,g.slug,g.name]);await query('insert into guild_settings(guild_id,layout_json) values($1,$2)',[g.id,JSON.stringify({game:'forever',sourceGuild:'lichtloot'})]);}
await query('insert into guild_master_codes(guild_id,master_code) values($1,$2)',[guild.id,'TESTMASTER']);
for(const [id,gid] of [[player,guild.id],[foreign,other.id]])await query("insert into players(id,guild_id,player_pin) values($1,$2,'PRIVATE123')",[id,gid]);
const char=randomUUID();await query("insert into forever_characters(id,guild_id,player_id,name,ruleset,class_name,role) values($1,$2,$3,'Ariee Mondlichtung','normal','priest','heal')",[char,guild.id,player]);
const api=createForeverRaids({query,pool}),access=createForeverAccess(query),lead={canManage:true,canAdmin:true,label:'Leitung'};
await assert.rejects(access.requireGuild('era'),e=>e.statusCode===404);
await assert.rejects(access.authorize(guild,{masterCode:'WRONG'}),e=>e.statusCode===403);
await assert.rejects(access.authorize(guild,{playerPin:'PRIVATE123'}),e=>e.statusCode===403);
assert.equal((await access.authorize(guild,{masterCode:'TESTMASTER'})).canAdmin,true);
assert.equal((await api.run(guild,{canManage:true},{action:'adminOverview'})).actor.canAdmin,false);
await assert.rejects(api.run(guild,{canManage:true},{action:'adminSettings'}),e=>e.statusCode===403);
await assert.rejects(api.run(guild,lead,{action:'adminPlayer',playerId:foreign,operation:'approve'}),e=>e.statusCode===404);
await api.run(guild,lead,{action:'adminPlayer',playerId:player,operation:'approve'});
assert.equal((await access.authorize(guild,{playerPin:'PRIVATE123'})).label,'Ariee Mondlichtung');
await assert.rejects(api.run(guild,lead,{action:'adminPlayer',playerId:player,operation:'approve'}),e=>e.statusCode===409);
await api.run(guild,lead,{action:'adminPlayer',playerId:player,operation:'block'});
await assert.rejects(access.authorize(guild,{playerPin:'PRIVATE123'}),e=>e.statusCode===403);
await api.run(guild,lead,{action:'adminPlayer',playerId:player,operation:'unblock'});
await api.run(guild,lead,{action:'adminPlayer',playerId:player,operation:'role',role:'gildenleitung'});
assert.equal((await access.authorize(guild,{playerPin:'PRIVATE123'})).canAdmin,true);
await assert.rejects(api.run(guild,{...lead,playerId:player},{action:'adminPlayer',playerId:player,operation:'block'}),/eigenen Zugang/);
await assert.rejects(api.run(guild,lead,{action:'adminSettings',name:'Name',discordUrl:'https://evil.test',revision:0}),/discord/i);
await api.run(guild,lead,{action:'adminSettings',name:'Neuer Name',rules:'Regeln',discordUrl:'https://discord.gg/test',revision:0});
await assert.rejects(api.run(guild,lead,{action:'adminSettings',name:'Stale',revision:0}),e=>e.statusCode===409);
const overview=await api.run(guild,lead,{action:'adminOverview'});assert.equal(overview.players.length,1);assert.equal(overview.settings.rules,'Regeln');assert.ok(!JSON.stringify(overview).includes('PRIVATE123'));assert.ok(!JSON.stringify(overview).includes('TESTMASTER'));
assert.equal((await query('select layout_json from guild_settings where guild_id=$1',[guild.id])).rows[0].layout_json.sourceGuild,'lichtloot');
assert.equal((await api.run(other,lead,{action:'adminOverview'})).history.length,0);
if(!process.env.FOREVER_DATABASE_URL)assert.throws(()=>foreverQuery('select 1'),e=>e.statusCode===503);
await assert.rejects(query('insert into forever_priority_entries(guild_id,character_id,raid_id,item_id,priority) values($1,$2,$3,123,1)',[other.id,char,randomUUID()]),/foreign key/);
await db.close();console.log('Forever admin/database tests passed: isolated auth, approval, roles, blocked access, cross-guild rejection, settings revisions, audit, secret redaction, no Era fallback, loot foreign keys.');
