// Run with PGlite installed in a test runtime: FOREVER_PGLITE=/absolute/path/to/dist/index.js node tests/forever-raids.test.mjs
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createForeverRaids,raidInput} from '../src/forever-raids.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec('create table guilds(id uuid primary key);create table players(id uuid primary key,guild_id uuid not null);create table guild_settings(guild_id uuid,layout_json jsonb);');
const g={id:randomUUID(),slug:'guild-a',name:'Gilde A'}, other={id:randomUUID(),slug:'guild-b',name:'Gilde B'};
for(const guild of [g,other])await db.query('insert into guilds(id) values($1)',[guild.id]);
const a={playerId:randomUUID(),label:'Anna',canManage:false},b={playerId:randomUUID(),label:'Ben',canManage:false}, outsider={playerId:randomUUID(),label:'Other',canManage:false},lead={playerId:null,label:'Gildenleitung',canManage:true};
for(const [actor,guild] of [[a,g],[b,g],[outsider,other]])await db.query('insert into players values($1,$2)',[actor.playerId,guild.id]);
const query=(sql,params=[])=>params.length?db.query(sql,params):sql.includes('create table')?db.exec(sql):db.query(sql);
const service=createForeverRaids({query,pool:{connect:async()=>({query:(...args)=>db.query(...args),release(){}})}});
const run=(actor,action,body={},guild=g)=>service.run(guild,actor,{...body,action});
const ca=(await run(a,'saveCharacter',{name:'Aria',className:'mage',role:'dd',ruleset:'normal'})).id;
const cb=(await run(b,'saveCharacter',{name:'Borin',className:'warrior',role:'tank',ruleset:'normal'})).id;
const cc=(await run(outsider,'saveCharacter',{name:'Aria',className:'druid',role:'heal',ruleset:'normal'},other)).id;
assert.notEqual(ca,cc);
await assert.rejects(run(b,'saveCharacter',{id:ca,name:'Stolen',className:'mage',role:'dd',ruleset:'normal'}),/Eigener Charakter/);
await assert.rejects(run(a,'saveCharacter',{name:'Borin',className:'mage',role:'dd',ruleset:'normal'}),/bereits vergeben/);
const group=(await run(lead,'saveGroup',{name:'Freitagsraid'})).id;
const foreignGroup=(await run(lead,'saveGroup',{name:'Freitagsraid'},other)).id;
const params={title:'Forever Abend',kind:'other',date:'2099-01-02',time:'20:00',size:1,tanks:1,heals:0,description:'Treffpunkt',groupId:group};
assert.throws(()=>raidInput({...params,date:'2027-02-30'}));
assert.throws(()=>raidInput({...params,tanks:2}));
await assert.rejects(run(a,'saveRaid',params),/Nur die/);
await assert.rejects(run(lead,'saveRaid',{...params,groupId:foreignGroup}),/gehört nicht/);
const raidId=(await run(lead,'saveRaid',params)).id;
await assert.rejects(run(outsider,'signup',{raidId,characterId:cc,role:'heal',status:'signed'},other),/nicht gefunden/);
await assert.rejects(run(a,'signup',{raidId,characterId:cb,role:'dd',status:'signed'}),/gehört nicht/);
assert.equal((await run(a,'signup',{raidId,characterId:ca,role:'dd',status:'signed'})).status,'signed');
assert.equal((await run(b,'signup',{raidId,characterId:cb,role:'tank',status:'signed'})).status,'bench');
let overview=await run(a,'overview');
assert.equal(overview.raids.length,1);assert.equal(overview.characters.length,1);assert.equal(overview.raids[0].signups.filter(s=>s.mine).length,1);
assert.equal(overview.raids[0].date,'2099-01-02');assert.equal(overview.raids[0].time,'20:00');
assert.equal((await run(outsider,'overview',{},other)).raids.length,0);
await assert.rejects(run(lead,'manageSignup',{raidId,characterId:cb,role:'tank',status:'signed'}),/Alle Plätze/);
await run(a,'signup',{raidId,characterId:ca,role:'dd',status:'absent'});
await run(lead,'manageSignup',{raidId,characterId:cb,role:'tank',status:'signed'});
overview=await run(a,'overview');assert.equal(overview.raids[0].signups.filter(s=>s.status==='signed').length,1);
await assert.rejects(run(a,'history',{raidId}),/Nur die/);
assert.equal((await run(lead,'history',{raidId},{...other})).history.length,0);
assert.ok((await run(lead,'history',{raidId})).history.length>=5);
await run(lead,'saveRaid',{...params,id:raidId,revision:1,status:'closed'});
await assert.rejects(run(lead,'saveRaid',{...params,id:raidId,revision:1}),/inzwischen geändert/);
await assert.rejects(run(a,'signup',{raidId,characterId:ca,role:'dd',status:'signed'}),/geschlossen/);
await run(lead,'saveRaid',{...params,id:raidId,revision:2,status:'completed'});
assert.equal((await run(a,'overview')).raids.length,0);
assert.equal((await run(a,'overview',{archive:true})).raids.length,1);
assert.equal((await run(outsider,'overview',{archive:true},other)).raids.length,0);
console.log('Forever: real PostgreSQL queries passed — guild isolation, ownership, capacity, role authorization, revisions, status and audit.');
await db.close();
