import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createForeverRaids,foreverSchema} from '../src/forever-raids.js';
import {createForeverAccess} from '../src/forever-db.js';
import {createForeverDiscord} from '../src/forever-discord.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE||'@electric-sql/pglite');
const db=new PGlite();await db.exec(await readFile(new URL('../src/forever-core.sql',import.meta.url),'utf8'));await db.exec(foreverSchema);
const query=(s,p=[])=>p.length?db.query(s,p):db.exec(s).then(r=>r.at(-1));const pool={connect:async()=>({query,release(){}})};
const first={id:randomUUID(),slug:'beta-test',name:'Beta'},second={id:randomUUID(),slug:'other',name:'Other'};
for(const g of [first,second]){await query('insert into guilds(id,slug,name) values($1,$2,$3)',[g.id,g.slug,g.name]);await query('insert into guild_settings(guild_id,layout_json) values($1,$2)',[g.id,JSON.stringify({game:'forever',forever:{rules:'Keep these rules',revision:7}})]);}
const lead={canManage:true,canAdmin:true,label:'Leitung'},member={canManage:false,canAdmin:false,label:'Mitglied'};
const raids=createForeverRaids({pool,query});const call=(g,a,action,body={})=>raids.run(g,a,{action,...body});
await call(first,lead,'adminAnnouncement',{title:'Raid',message:'Freitag'});
assert.equal((await call(first,member,'overview')).settings.announcement.message,'Freitag');
assert.equal((await call(second,member,'overview')).settings.announcement,null);
const overview=await call(first,lead,'adminOverview');assert.equal(overview.settings.rules,'Keep these rules');assert.equal(overview.settings.revision,7);
await assert.rejects(call(first,member,'adminAnnouncement',{title:'Wrong',message:'No'}),e=>e.statusCode===403);
await assert.rejects(call(first,lead,'adminAnnouncement',{title:'Only title'}),e=>e.statusCode===400);
await assert.rejects(call(first,lead,'adminDiscordTest'),e=>e.statusCode===409);
await query('insert into forever_discord_channels(guild_id,discord_guild_id,channel_id) values($1,$2,$3)',[first.id,'111111111111111111','222222222222222222']);
await call(first,lead,'adminDiscordTest',{channelId:'999999999999999999'});
await assert.rejects(call(first,lead,'adminDiscordTest'),e=>e.statusCode===429);
await assert.rejects(call(first,member,'adminDiscordCheck'),e=>e.statusCode===403);
const bot=createForeverDiscord({pool,query,raids,access:createForeverAccess(query)});
const jobs=(await bot.run({action:'diagnosticsPoll'})).jobs;assert.equal(jobs.length,1);assert.equal(jobs[0].channel_id,'222222222222222222');
assert.equal((await bot.run({action:'diagnosticsPoll'})).jobs.length,0);
await assert.rejects(bot.run({action:'diagnosticsAck',id:jobs[0].id,leaseToken:randomUUID(),result:{testSent:true}}),e=>e.statusCode===409);
await bot.run({action:'diagnosticsAck',id:jobs[0].id,leaseToken:jobs[0].lease_token,result:{bot:true,server:true,channel:true,permissions:true,testSent:true,messageId:'333333333333333333'}});
assert.equal((await call(first,lead,'adminOverview')).discordCheck.result.testSent,true);
assert.equal((await call(second,lead,'adminOverview')).discordCheck,null);
await call(first,lead,'adminAnnouncement',{title:'',message:''});assert.equal((await call(first,member,'overview')).settings.announcement.message,'');
assert.deepEqual((await call(first,lead,'adminPlayerAnalysis')).players,[]);
await db.close();console.log('PASS: Forever bulletin isolation, roles, preserved settings, Discord destination isolation, cooldown and worker lease acknowledgement.');
