import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {createForeverRaids} from '../src/forever-raids.js';
import {createForeverAccess} from '../src/forever-db.js';
import {createBetaAccess,betaName,verifyBetaPin} from '../src/forever-beta-access.js';
import {createForeverDiscord} from '../src/forever-discord.js';
const db=new PGlite();await db.exec(await readFile(new URL('../src/forever-core.sql',import.meta.url),'utf8'));
const query=(s,p=[])=>p.length?db.query(s,p):db.exec(s).then(r=>r.at(-1)),pool={connect:async()=>({query,release(){}})};
const guild={id:randomUUID(),slug:'sandkasten',name:'Elternabend'};
await query('insert into guilds(id,slug,name) values($1,$2,$3)',[guild.id,guild.slug,guild.name]);
await query('insert into guild_settings(guild_id,layout_json) values($1,$2)',[guild.id,'{"game":"forever"}']);
process.env.FOREVER_BETA_PINS=JSON.stringify({sandkasten:'12345678'});
const raids=createForeverRaids({pool,query}),beta=createBetaAccess({pool,query,raids}),access=createForeverAccess(query);
const regular=access.authorize;access.authorize=(g,b)=>b.betaPin!==undefined?beta.authorize(g,b):regular(g,b);
const body={betaPin:'12345678',characterName:'Aria',className:'mage'},lead={canAdmin:true,canManage:true,label:'Leitung'};
assert.throws(()=>verifyBetaPin({slug:'other'},body.betaPin));assert.throws(()=>betaName('<script>'));
await assert.rejects(beta.authorize(guild,{...body,betaPin:'wrong'}),e=>e.statusCode===403);
const a=await beta.authorize(guild,body),again=await beta.authorize(guild,{...body,characterName:' aria '});assert.equal(a.playerId,again.playerId);assert.equal(a.canAdmin,false);
const p=(await query('select * from players where id=$1',[a.playerId])).rows[0];await assert.rejects(regular(guild,{playerPin:p.player_pin}),e=>e.statusCode===403);
const view=await raids.run(guild,a,{action:'overview'});assert.equal(view.actor.isBeta,true);assert.equal(view.characters.length,1);assert.ok(view.layout);
const params={title:'Todesminen',kind:'deadmines',date:'2099-01-02',time:'20:00',size:1,tanks:0,heals:0};
const r=await raids.run(guild,lead,{...params,action:'saveRaid'});
const signup={action:'signup',raidId:r.id,characterId:a.betaCharacterId,role:'dd',status:'signed'};
assert.equal((await raids.run(guild,a,signup)).status,'signed');
const b=await beta.authorize(guild,{...body,characterName:'Borin',className:'warrior'});
assert.equal((await raids.run(guild,b,{...signup,characterId:b.betaCharacterId})).status,'bench');
await assert.rejects(raids.run(guild,b,signup),e=>e.statusCode===403);
const large=await raids.run(guild,lead,{...params,kind:'hyjal',action:'saveRaid'});await assert.rejects(raids.run(guild,a,{...signup,raidId:large.id}),e=>e.statusCode===403);
await assert.rejects(raids.run(guild,a,{action:'saveRaid',...params}),e=>e.statusCode===403);
await assert.rejects(raids.run(guild,a,{action:'saveCharacter',name:'Changed'}),e=>e.statusCode===403);
const owner=randomUUID();await query("insert into players(id,guild_id,player_pin,approval_status) values($1,$2,'NORMAL','approved')",[owner,guild.id]);await raids.run(guild,{playerId:owner,label:'Regular'},{action:'saveCharacter',name:'Regular',className:'mage',role:'dd',ruleset:'normal'});
await assert.rejects(beta.authorize(guild,{...body,characterName:'Regular'}),e=>e.statusCode===409);
const bot=createForeverDiscord({pool,query,access,raids});await bot.run({action:'poll'});
const ctx={guild:guild.slug,raidId:r.id,messageId:'1521902200203247000',channelId:'1521902200203247616',discordGuildId:'1116103206439768154',discordUserId:'1521902200203247111'};
await query('insert into forever_discord_posts(guild_id,raid_id,discord_guild_id,channel_id,message_id) values($1,$2,$3,$4,$5)',[guild.id,r.id,ctx.discordGuildId,ctx.channelId,ctx.messageId]);
assert.equal((await bot.run({action:'poll'})).posts[0].betaEnabled,true);
const dc=await bot.run({...ctx,...body,action:'betaContext'});assert.equal(dc.characters[0].id,a.betaCharacterId);assert.ok(dc.raid.signups.some(s=>s.mine));
await assert.rejects(bot.run({...ctx,...body,action:'betaContext',messageId:'1521902200203247999'}),e=>e.statusCode===403);
await bot.run({...ctx,...body,action:'betaSignup',role:'dd',status:'absent'});
assert.equal((await raids.run(guild,a,{action:'overview'})).raids.find(x=>x.id===r.id).signups.find(x=>x.mine).status,'absent');
assert.equal((await query('select * from forever_discord_links')).rows.length,0);
assert.ok(!JSON.stringify(await bot.run({action:'poll'})).includes(body.betaPin));
await db.close();console.log('Beta access passed: shared website/Discord identity, PIN scope, normal page, capacity, existing-account protection, permissions and post binding.');
