import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createInvitations} from '../src/forever-invitations.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE||'@electric-sql/pglite');const db=new PGlite(),gid=randomUUID(),rid=randomUUID();
await db.exec(`create table guilds(id uuid primary key);create table forever_raids(guild_id uuid,id uuid,title text,starts_at timestamptz,description text,status text,deleted_at timestamptz,primary key(guild_id,id));create table forever_discord_posts(guild_id uuid,raid_id uuid,message_id text,channel_id text,discord_guild_id text);`);await db.query('insert into guilds values($1)',[gid]);await db.query("insert into forever_raids values($1,$2,'Event',now()+interval '40 days','Text','open',null)",[gid,rid]);await db.query("insert into forever_discord_posts values($1,$2,'111111111111111111','222222222222222222','333333333333333333')",[gid,rid]);
let admin=true;const service=createInvitations({query:(...a)=>db.query(...a),eraQuery:async sql=>({rows:sql.includes('discord_bot_roles')?[{id:'777777777777777777',name:'Raidmitglieder',source:'lichtloot'}]:[{id:'444444444444444444',name:'Lichtspieler',source:'lichtloot',roles:['777777777777777777']},{id:'555555555555555555',name:'Nachtspieler',source:'nachtloot'}]}),pool:{connect:async()=>({query:(...a)=>db.query(...a),release(){}})},access:{requireGuild:async slug=>({id:gid,slug}),authorize:async()=>({canAdmin:admin})}});
const b={guild:'lichtbringer-forever',raidId:rid,action:'list'};assert.equal((await service.run(b)).members.length,2);assert.equal((await service.run(b)).roles[0].name,'Raidmitglieder');assert.deepEqual((await service.run(b)).members[0].roles,['777777777777777777']);admin=false;await assert.rejects(service.run(b),/Nur die/);admin=true;await assert.rejects(service.run({...b,guild:'other'}),/Nur die/);await assert.rejects(service.run({...b,raidId:randomUUID()}),/nicht gefunden/);
const send={...b,action:'send',recipients:['444444444444444444','555555555555555555'],message:'Einladung zum gemeinsamen Gründungsabend'};await assert.rejects(service.run({...send,recipients:['999999999999999999']}),/auswählen/);assert.match((await service.run(send)).message,/2 Einladungen/);assert.match((await service.run(send)).message,/0 Einladungen/);
const jobs=(await service.bot({action:'invitationPoll'})).jobs;assert.equal(jobs.length,2);assert.equal((await service.bot({action:'invitationPoll'})).jobs.length,0);await service.bot({action:'invitationAck',id:jobs[0].id,success:true,messageId:'666666666666666666'});await service.bot({action:'invitationAck',id:jobs[1].id,success:false,error:'DM gesperrt'});const rows=(await service.run(b)).deliveries;assert.deepEqual(rows.map(x=>x.status).sort(),['failed','sent']);const sentId=jobs[0].recipient_id;
assert.match((await service.run({...send,recipients:[sentId],message:'Aktualisierte Einladung zum Gründungsabend'})).message,/1 Einladungen/);
assert.equal((await service.bot({action:'invitationPoll'})).jobs.length,0); // Old workers must never send a second DM.
const editJobs=(await service.bot({action:'invitationPoll',workerVersion:2})).jobs;assert.equal(editJobs.length,1);assert.equal(editJobs[0].message_id,'666666666666666666');
assert.match((await service.run({...send,recipients:[sentId],message:'Concurrent changed content'})).message,/0 Einladungen/);
await service.bot({action:'invitationAck',id:editJobs[0].id,success:false,error:'Nachricht fehlt'});
assert.equal((await service.run(b)).deliveries.find(x=>x.recipient_id===sentId).message_id,'666666666666666666');
assert.match((await service.run({...send,recipients:[jobs[1].recipient_id],message:'Do not retry unknown sends'})).message,/0 Einladungen/);
await db.close();console.log('Invitation tests passed: names from both guilds, admin scope, raid scope, recipient validation, deduplication, claim-once and delivery status.');
