import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createEraImport} from '../src/forever-era-import.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE||'@electric-sql/pglite');
const era=new PGlite(),db=new PGlite();
const schema=`create table guilds(id uuid primary key,slug text);create table players(id uuid primary key,guild_id uuid references guilds(id),player_pin text,role text,approval_status text,is_blocked boolean default false,security_question text,security_answer text,unique(guild_id,player_pin));`;
await era.exec(schema);await db.exec(schema);
const gid=randomUUID(),sid=randomUUID(),pid=randomUUID(),other=randomUUID();
await db.query('insert into guilds values($1,$2)',[gid,'lichtbringer-forever']);await era.query('insert into guilds values($1,$2)',[sid,'lichtloot']);
await era.query("insert into players(id,guild_id,player_pin,role,approval_status,security_question,security_answer) values($1,$2,'OLD4','gildenleitung','approved','question','hash')",[pid,sid]);
const run=createEraImport({eraQuery:(...a)=>era.query(...a),query:(...a)=>db.query(...a),pool:{connect:async()=>({query:(...a)=>db.query(...a),release(){}})},requireGuild:async()=>({id:gid})});
const b={guild:'lichtbringer-forever',sourceGuild:'lichtloot',playerPin:'old4'};
await assert.rejects(run({...b,playerPin:'WRONG'}),/nicht bestätigt/);
await assert.rejects(run({...b,guild:'elternabend'}),/nur von/);
await assert.rejects(run({...b,sourceGuild:'other'}),/nur von/);
assert.equal((await run(b)).success,true);
let p=(await db.query('select * from players')).rows[0];assert.equal(p.role,'member');assert.equal(p.player_pin,'OLD4');assert.equal(p.approval_status,'approved');assert.equal(p.security_answer,'hash');
assert.equal((await run(b)).alreadyImported,true);assert.equal((await db.query('select * from players')).rows.length,1);
await db.query("update players set player_pin='NEWCODE' where id=$1",[p.id]);assert.equal((await run(b)).useExistingForeverCode,true);assert.equal((await db.query('select player_pin from players')).rows[0].player_pin,'NEWCODE');
await db.query('update players set is_blocked=true');await assert.rejects(run(b),/nicht freigegeben/);await db.query('update players set is_blocked=false');
await era.query('update players set is_blocked=true');await assert.rejects(run(b),/nicht bestätigt/);await era.query("update players set is_blocked=false,approval_status='pending'");await assert.rejects(run(b),/nicht bestätigt/);
await era.query("insert into players(id,guild_id,player_pin,role,approval_status) values($1,$2,'NEWCODE','member','approved')",[other,sid]);await assert.rejects(run({...b,playerPin:'NEWCODE'}),/bereits vergeben/);assert.equal((await db.query('select * from players')).rows.length,1);
assert.equal((await era.query('select role from players where id=$1',[pid])).rows[0].role,'gildenleitung');
await db.close();await era.close();console.log('Era import passed: credentials, scoping, member-only, idempotency, blocked/pending users, changed PIN preservation, collision rollback, isolated source.');
