import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createForeverRaids,foreverSchema} from '../src/forever-raids.js';
import {createForeverAccess} from '../src/forever-db.js';
import {createForeverDiscord,installForeverDiscord} from '../src/forever-discord.js';
const {PGlite}=await import(process.env.FOREVER_PGLITE||'@electric-sql/pglite'),db=new PGlite();
await db.exec(await readFile(new URL('../src/forever-core.sql',import.meta.url),'utf8'));await db.exec(foreverSchema);
const query=(s,p=[])=>p.length?db.query(s,p):db.exec(s).then(r=>r.at(-1)),pool={connect:async()=>({query,release(){}})};
const guild={id:randomUUID(),slug:'forever',name:'Test'},other={id:randomUUID(),slug:'other',name:'Andere'};
for(const g of [guild,other]){await query('insert into guilds(id,slug,name) values($1,$2,$3)',[g.id,g.slug,g.name]);await query('insert into guild_settings(guild_id,layout_json) values($1,$2)',[g.id,'{"game":"forever"}']);await query("insert into guild_master_codes(guild_id,master_code) values($1,'TESTMASTER')",[g.id]);}
const players=[randomUUID(),randomUUID()],chars=[randomUUID(),randomUUID()];
for(let i=0;i<2;i++){await query("insert into players(id,guild_id,player_pin,approval_status) values($1,$2,$3,'approved')",[players[i],guild.id,'PRIVATE'+i]);await query("insert into forever_characters(id,guild_id,player_id,name,ruleset,class_name,role) values($1,$2,$3,$4,'normal','priest','heal')",[chars[i],guild.id,players[i],'Spieler '+i]);}
const raids=createForeverRaids({pool,query}),access=createForeverAccess(query),bot=createForeverDiscord({pool,query,access,raids}),lead={canManage:true,canAdmin:true,label:'Leitung'};
const r=await raids.run(guild,lead,{action:'saveRaid',title:'Test',date:'2030-09-20',time:'20:00',size:1,tanks:0,heals:1,kind:'hyjal'});
await assert.rejects(raids.run(guild,{canManage:false},{action:'discordPublish',raidId:r.id}),e=>e.statusCode===403);
await assert.rejects(raids.run(guild,lead,{action:'discordPublish',raidId:r.id}),/Verbinde/);
await assert.rejects(bot.run({action:'configure',guild:guild.slug,masterCode:'WRONG',channelId:'1521902200203247616',discordGuildId:'1116103206439768154'}),e=>e.statusCode===403);
await bot.run({action:'configure',guild:guild.slug,masterCode:'TESTMASTER',channelId:'1521902200203247616',discordGuildId:'1116103206439768154'});
await raids.run(guild,lead,{action:'discordPublish',raidId:r.id});await raids.run(guild,lead,{action:'discordPublish',raidId:r.id});
assert.equal((await bot.run({action:'poll'})).posts.length,1);
const claim=await bot.run({action:'claim',guild:guild.slug,raidId:r.id});assert.ok(claim.leaseToken);assert.equal((await bot.run({action:'claim',guild:guild.slug,raidId:r.id})).leaseToken,null);
await assert.rejects(bot.run({action:'ack',guild:guild.slug,raidId:r.id,leaseToken:randomUUID(),messageId:'1521902200203247000',hash:'hash'}),e=>e.statusCode===409);
await bot.run({action:'ack',guild:guild.slug,raidId:r.id,leaseToken:claim.leaseToken,messageId:'1521902200203247000',hash:'hash'});
const ctx={guild:guild.slug,raidId:r.id,messageId:'1521902200203247000',channelId:'1521902200203247616',discordGuildId:'1116103206439768154',discordUserId:'1521902200203247111'};
await assert.rejects(bot.run({action:'context',...ctx}),e=>e.statusCode===401);
await assert.rejects(bot.run({action:'connect',...ctx,channelId:'1521902200203247999',playerPin:'PRIVATE0'}),e=>e.statusCode===403);
await assert.rejects(bot.run({action:'connect',...ctx,guild:other.slug,playerPin:'PRIVATE0'}),e=>e.statusCode===403);
const connected=await bot.run({action:'connect',...ctx,playerPin:'PRIVATE0'});assert.equal(connected.characters.length,1);
await assert.rejects(bot.run({action:'connect',...ctx,discordUserId:'1521902200203247222',playerPin:'PRIVATE0'}),e=>e.statusCode===409);
await assert.rejects(bot.run({action:'signup',...ctx,characterId:chars[1],role:'heal',status:'signed'}),e=>e.statusCode===403);
assert.equal((await bot.run({action:'signup',...ctx,characterId:chars[0],role:'heal',status:'signed'})).status,'signed');
const second={...ctx,discordUserId:'1521902200203247222'};await bot.run({action:'connect',...second,playerPin:'PRIVATE1'});
assert.equal((await bot.run({action:'signup',...second,characterId:chars[1],role:'heal',status:'signed'})).status,'bench');
const poll=await bot.run({action:'poll'});assert.equal(poll.posts[0].raid.signups.length,2);assert.ok(!JSON.stringify(poll).includes('PRIVATE'));assert.ok(!JSON.stringify(poll).includes('TESTMASTER'));
await query('update players set is_blocked=true where id=$1',[players[0]]);await assert.rejects(bot.run({action:'context',...ctx}),e=>e.statusCode===401);
await bot.run({action:'unlink',...second});await assert.rejects(bot.run({action:'context',...second}),e=>e.statusCode===401);
let handler;installForeverDiscord({post(_,fn){handler=fn;}},{pool,query,access,raids,token:'SECRET'});let error;await handler({headers:{},body:{action:'poll'}},{set(){}},e=>error=e);assert.equal(error.statusCode,403);
await db.close();console.log('Forever Discord passed: token required, admin publication, idempotent post, leases, exact message/channel/guild binding, account linking, blocked accounts, character ownership, shared capacity, no secrets in poll.');
