const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),vm=require('vm');
(async()=>{const {createGmailApi}=await import('../src/gmail-api.js');const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();const env={GMAIL_USER:'support@example.com',GMAIL_OAUTH_CLIENT_ID:'test-client',GMAIL_OAUTH_CLIENT_SECRET:'test-secret',GMAIL_TOKEN_KEY:Buffer.alloc(32,1).toString('base64')};let calls=[],account='support@example.com',mode='ok',checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};
const mock=async(url,o)=>{calls.push({url,o});if(url.includes('/token')){if(mode==='revoked')return {ok:false,status:400,json:async()=>({error:'invalid_grant'})};return {ok:true,json:async()=>({access_token:'access',refresh_token:'refresh',scope:'openid email https://www.googleapis.com/auth/gmail.send'})};}if(url.includes('userinfo'))return {ok:true,json:async()=>({email:account,email_verified:true})};if(url.includes('messages/send')){if(mode==='network')throw Error('unavailable');if(mode==='reject')return {ok:false,status:403,json:async()=>({error:{message:'sensitive details'}})};return {ok:true,json:async()=>({id:'gmail-message'})};}throw Error('unexpected URL');};
const api=createGmailApi({query:(q,p)=>db.query(q,p),env,fetchImpl:mock});eq((await api.status()).connected,false);await assert.rejects(()=>api.sendMail({to:'player@example.com',text:'test'}),e=>e.code==='GMAIL_NOT_READY');checks++;
let start=await api.start(),url=new URL(start.url);eq(url.searchParams.get('scope'),'openid email https://www.googleapis.com/auth/gmail.send');eq(url.searchParams.get('code_challenge_method'),'S256');eq(url.searchParams.get('access_type'),'offline');eq(url.searchParams.get('login_hint'),env.GMAIL_USER);
await assert.rejects(()=>api.callback({state:url.searchParams.get('state'),code:'code',binding:'wrong'}));checks++;
await api.callback({state:url.searchParams.get('state'),code:'code',binding:start.binding});eq((await api.status()).connected,true);eq((await db.query('select refresh_token from platform_gmail_connection')).rows[0].refresh_token.includes('refresh'),false);await assert.rejects(()=>api.callback({state:url.searchParams.get('state'),code:'code',binding:start.binding}));checks++;
eq((await api.verify()).verified,true);eq(calls.filter(c=>c.url.includes('messages/send')).length,0);
let result=await api.sendMail({from:'attacker@example.com',to:'player@example.com',subject:'Antwort äöü',text:'Hallo\nAntwort',attachments:[{filename:'test.png',content:Buffer.from('PNG'),contentType:'image/png'}]});eq(result.messageId,'gmail-message');const mail=Buffer.from(JSON.parse(calls.at(-1).o.body).raw,'base64url').toString();eq(mail.includes('support@example.com'),true);eq(mail.includes('attacker@example.com'),false);eq(mail.includes('player@example.com'),true);eq(mail.includes('multipart/mixed'),true);eq(mail.includes('test.png'),true);
mode='reject';await assert.rejects(()=>api.sendMail({to:'player@example.com',text:'test'}),e=>e.code==='GMAIL_REJECTED'&&!e.message.includes('sensitive'));checks++;mode='network';await assert.rejects(()=>api.sendMail({to:'player@example.com',text:'test'}),e=>e.code==='GMAIL_UNKNOWN');checks++;mode='revoked';const before=calls.filter(c=>c.url.includes('messages/send')).length;await assert.rejects(()=>api.sendMail({to:'player@example.com',text:'test'}),e=>e.code==='GMAIL_AUTH');checks++;eq(calls.filter(c=>c.url.includes('messages/send')).length,before);
mode='ok';start=await api.start();account='wrong@example.com';await assert.rejects(()=>api.callback({state:new URL(start.url).searchParams.get('state'),code:'code',binding:start.binding}),e=>e.code==='GMAIL_AUTH');checks++;eq((await api.status()).email,'support@example.com');
const empty=createGmailApi({query:(q,p)=>db.query(q,p),env:{},fetchImpl:mock});eq((await empty.status()).configured,false);await assert.rejects(()=>empty.start(),e=>e.code==='GMAIL_NOT_READY');checks++;
for(const f of ['admin.html','lichtloot-api/public/admin.html','lichtloot-api/src/admin.html']){for(const m of fs.readFileSync(path.join(__dirname,'../..',f),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);checks++;}
await db.close();console.log(checks+' Gmail API/OAuth/MIME checks passed; Google calls mocked, no email sent.');})().catch(e=>{console.error(e);process.exit(1)});
