const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');const src=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');function fn(name){const start=src.search(new RegExp('(?:async )?function '+name+'\\(')),tail=src.slice(start),m=tail.slice(1).search(/\n(?:(?:async )?function |app\.)/);assert(start>=0,name);return m<0?tail:tail.slice(0,m+1)};
(async()=>{const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};await db.exec(`create table guilds(id uuid primary key,slug text,name text);create table players(id uuid primary key,guild_id uuid,player_pin text,security_question text,security_answer text,updated_at timestamptz default now(),is_blocked boolean default false,blocked_reason text,blocked_at timestamptz,approval_status text default 'approved',role text,permissions jsonb,notification_discord_names text,unique(guild_id,player_pin));create table characters(id uuid primary key,player_id uuid,name text,server text,class_name text,is_main boolean default false,created_at timestamptz default now());create table issue_reports(id uuid primary key,guild_id uuid,category text,status text,resolved_at timestamptz,updated_at timestamptz default now(),created_at timestamptz default now(),reference_id text,action_name text,page text,note text,technical_details text,player text,raid text);`);
const uuid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;await db.query("insert into guilds values($1,'lichtloot','Lichtbringer'),($2,'nachtloot','Nachtwächter')",[uuid(1),uuid(2)]);
for(const [n,q,a,pin] of [[10,'pet','Mäxchen','ALT1'],[11,'Raidlead-Eintrag','placeholder','ALT2'],[12,null,null,'ALT3'],[13,'food','Pizza','BELEGT'],[14,'Wie hieß dein erstes Haustier?','Fido','ALT4']]){await db.query('insert into players(id,guild_id,player_pin,security_question,security_answer) values($1,$2,$3,$4,$5)',[uuid(n),uuid(1),pin,q,a]);await db.query("insert into characters(id,player_id,name,server) values($1,$2,$3,'Everlook')",[uuid(n+20),uuid(n),'Test'+n]);}
const ctx=vm.createContext({query:(s,p)=>db.query(s,p),clean:v=>String(v||'').trim(),normalizePin:v=>String(v||'').trim().toUpperCase(),ensureCrossGuildPlayerLogin:async()=>{},normalizePlayerApprovalStatus:v=>v,normalizeCharacter:v=>v,isUuid:v=>/^[a-f0-9-]{36}$/i.test(v),requirePlatformMasterCode:v=>{if(v!=='platform'){const e=Error('Unauthorized');e.statusCode=403;throw e}}});vm.runInContext(['normalizePlayerSecurityQuestion','resetPlayerPinBySecurity','getCharactersByPin','normalizeIssueReportRow','getSystemErrors','updateSystemError'].map(fn).join('\n'),ctx);
const request={guildId:uuid(1),charName:'Test10',server:'Everlook',securityQuestion:'pet',securityAnswer:'MÄXCHEN',newPin:'neu1'};
eq(await ctx.resetPlayerPinBySecurity(request),'NEU1');eq((await ctx.getCharactersByPin(uuid(1),'NEU1')).length,1);eq((await ctx.getCharactersByPin(uuid(1),'ALT1')).length,0);
for(const [change,status] of [[{securityAnswer:'wrong'},403],[{securityQuestion:'food'},403],[{guildId:uuid(2)},404],[{newPin:'X'},400],[{newPin:'TOO-LONG-123'},400],[{newPin:'BELEGT'},409],[{charName:'Test11'},409],[{charName:'Test12'},409]]){await assert.rejects(()=>ctx.resetPlayerPinBySecurity({...request,...change}),e=>e.statusCode===status);checks++;}
eq((await ctx.getCharactersByPin(uuid(1),'NEU1')).length,1);eq(await ctx.resetPlayerPinBySecurity({...request,charName:'Test14',securityAnswer:'fido',newPin:'NEU4'}),'NEU4');
for(const [n,g,status,category] of [[40,1,'new','system_error'],[41,2,'checked','system_error'],[42,1,'resolved','system_error'],[43,1,'new','message']])await db.query("insert into issue_reports(id,guild_id,category,status,reference_id,note) values($1,$2,$3,$4,$5,'Testfehler')",[uuid(n),uuid(g),category,status,'ERR-'+n]);
let result=await ctx.getSystemErrors({query:{masterCode:'platform'}});eq(result.errors.length,2);eq(result.openCount,2);eq(new Set(result.errors.map(e=>e.guildSlug)).size,2);
result=await ctx.getSystemErrors({query:{masterCode:'platform',guildFilter:'nachtloot',status:'all',search:'ERR-41'}});eq(result.errors.length,1);eq(result.errors[0].guildName,'Nachtwächter');
await assert.rejects(()=>ctx.getSystemErrors({query:{masterCode:'guild-only'}}),e=>e.statusCode===403);checks++;
await assert.rejects(()=>ctx.updateSystemError({guildId:null,query:{masterCode:'guild-only',id:uuid(40),status:'resolved'}}),e=>e.statusCode===403);checks++;
eq((await ctx.updateSystemError({guildId:null,query:{masterCode:'platform',id:uuid(40),status:'resolved'}})).success,true);eq((await ctx.getSystemErrors({query:{masterCode:'platform'}})).openCount,1);eq((await ctx.updateSystemError({guildId:null,query:{masterCode:'platform',id:uuid(43),status:'resolved'}})).success,false);
for(const name of ['index.html','lichtloot-api/src/index.html','gildenleitung.html'])for(const m of fs.readFileSync(path.join(__dirname,'../..',name),'utf8').matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/\bsrc\s*=|application\/ld\+json|application\/json/.test(m[1]))continue;new vm.Script(m[2],{filename:name});checks++;}
await db.close();console.log(checks+' recovery, subsequent login, error-center authorization and syntax checks passed. No real account changes.');})().catch(e=>{console.error(e);process.exit(1)});
