import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPlayerAnalysis} from '../src/player-analysis/model.js';
import {getStoredPlayerAnalysis} from '../src/player-analysis/service.js';
const player=(name='Sintha',server='Everlook')=>({name,server,className:'Paladin',raidRole:'healer',healingDone:1000000,deaths:1});
const fight=(id,name,ms,healing,extra={})=>({id,name,isBoss:true,kill:true,durationMs:ms,players:{Sintha:{healingDone:healing,overheal:healing,damageDone:0,deaths:1,abilityCasts:{Cleanse:2,'Buff (uptime%)':99}},Peer:{healingDone:healing*2,overheal:0,damageDone:0,deaths:0}},...extra});
function row(id,date='2026-09-04',extra={}){return {id,raid:'NAXX',raid_date:date,generated_at:date,payload:{report:{raid:'Naxxramas',raidDate:date,reportCode:id},players:[player(),player('Peer')],fights:[fight(1,'Four Horsemen',100000,10000),fight(2,'Trash',100000,900000,{isBoss:false}),fight(3,'Wipe',100000,900000,{kill:false})],...extra}};}
const params={playerName:'Sintha',server:'Everlook',raid:'Naxxramas',count:5};
test('boss rate excludes trash and wipes despite polluted profile totals',()=>{const a=buildPlayerAnalysis([row('a')],params).analysis;assert.equal(a.raids[0].hps,100);assert.equal(a.raids[0].healing,10000);assert.equal(a.raids[0].rank,2);assert.equal(a.raids[0].casts.Cleanse,2);assert.equal(a.raids[0].casts['Buff (uptime%)'],undefined);assert.equal(a.count,1);assert.ok(a.observations.some(x=>x.title==='Weniger Teilnahmen verfügbar'));});
test('exact realm selection and canonical raid identity',()=>{const x=row('a');x.payload.players=[player('Sintha','Other')];assert.equal(buildPlayerAnalysis([x],{playerName:'Sintha',server:'Everlook'}).catalog.length,0);const y=row('b');y.payload.report.raid="Ruins of Ahn'Qiraj";assert.equal(buildPlayerAnalysis([y],{playerName:'Sintha',server:'Everlook'}).catalog[0].raid,'AQ20');});
test('last three chronological unique reports and repeated deaths',()=>{const rows=Array.from({length:6},(_,i)=>row(String(i),`2026-08-${10+i}`));const a=buildPlayerAnalysis([...rows,rows[5]],{...params,count:3}).analysis;assert.deepEqual(a.raids.map(r=>r.id),['3','4','5']);assert.ok(a.observations.some(x=>x.title.includes('Wiederkehrende Tode')));});
test('single report must be a matching participation',()=>{assert.throws(()=>buildPlayerAnalysis([row('a')],{...params,count:1,analysisId:'other'}));assert.throws(()=>buildPlayerAnalysis([row('a')],{...params,count:1}));assert.throws(()=>buildPlayerAnalysis([row('a')],{...params,count:500}));});
test('missing durations or metrics are unknown, never fabricated zero',()=>{const x=row('a');x.payload.fights=[fight(1,'Boss',null,10000)];let r=buildPlayerAnalysis([x],params).analysis.raids[0];assert.equal(r.hps,null);assert.equal(r.rank,null);x.payload.fights[0].durationMs=100000;delete x.payload.fights[0].players.Sintha.healingDone;r=buildPlayerAnalysis([x],params).analysis.raids[0];assert.equal(r.hps,null);});
test('peer ranking requires all of the same kills',()=>{const x=row('a');x.payload.fights.push(fight(4,'Other boss',100000,10000));delete x.payload.fights[3].players.Peer;assert.equal(buildPlayerAnalysis([x],params).analysis.raids[0].peerCount,1);});
test('database reads are parameterized and scoped to one guild',async()=>{let captured;await getStoredPlayerAnalysis({query:async(sql,args)=>{captured={sql,args};return {rows:[]};},guildId:'guild-test',params:{playerName:'Sintha',server:'Everlook'}});assert.match(captured.sql,/la.guild_id=\$1/);assert.deepEqual(captured.args,['guild-test','Sintha','Everlook']);});
