import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.PGLITE_MODULE);
const db=new PGlite();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.exec(`create table raids(id uuid primary key,guild_id uuid,name text,raid_date date,raid_time text);
create table characters(id uuid primary key,name text,server text);
create table items(id uuid primary key,name text);
create table prios(id uuid primary key,raid_id uuid references raids on delete cascade,character_id uuid references characters on delete cascade,p1_item_id uuid,p2_item_id uuid,p3_item_id uuid,comment text,bench text,created_at timestamptz default now(),updated_at timestamptz default now());`);
await db.query('insert into raids values($1,$2,$3,$4,$5)',[id(1),id(2),'MC','2026-09-08','21:30']);
await db.query('insert into characters values($1,$2,$3)',[id(3),'Mála','Everlook']);
await db.query('insert into items values($1,$2),($3,$4)',[id(4),'Magierklinge',id(5),'Feuerkern']);
await db.query('insert into prios(id,raid_id,character_id,p1_item_id,comment) values($1,$2,$3,$4,$5)',[id(6),id(1),id(3),id(4),'{"source":"railway","playerPin":"DO_NOT_STORE"}']);
const sql=await readFile(new URL('../migrations/041_prio_history.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
const history=async()=>(await db.query('select * from prio_history order by id')).rows;
assert.equal((await history()).length,1);assert.equal((await history())[0].operation,'BASELINE');
await db.query('/* prio-audit:savePrio */ update prios set p1_item_id=$1 where id=$2',[id(5),id(6)]);
let h=(await history()).at(-1);assert.equal(h.source,'savePrio');assert.equal(h.old_state.p1.name,'Magierklinge');assert.equal(h.new_state.p1.name,'Feuerkern');
await db.query('/* prio-audit:savePrio */ update prios set p1_item_id=null where id=$1',[id(6)]);
assert.equal((await history()).at(-1).new_state.p1.name,null);
await db.exec('begin');await db.query('delete from prios where id=$1',[id(6)]);await db.exec('rollback');assert.equal((await history()).length,3);
await db.query('/* prio-audit:deletePrio */ delete from prios where id=$1',[id(6)]);
assert.equal((await history()).at(-1).operation,'DELETE');
await db.query('/* prio-audit:savePrio */ insert into prios(id,raid_id,character_id,p1_item_id,comment) values($1,$2,$3,$4,$5)',[id(7),id(1),id(3),id(4),'invalid json']);
assert.equal((await history()).at(-1).operation,'INSERT');
await db.query('delete from raids where id=$1',[id(1)]);h=(await history()).at(-1);assert.equal(h.operation,'DELETE');assert.equal(h.guild_id,id(2));assert.equal(h.old_state.raidName,'MC');assert.equal(h.old_state.characterName,'Mála');
assert(!JSON.stringify(await history()).includes('DO_NOT_STORE'));
await db.close();console.log('PASS Prio history: idempotent baseline, insert/update/delete, source, old/new items, cleared items, rollback, cascade retention and PIN exclusion.');
