const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');
function fn(name){const start=src.search(new RegExp('(?:async )?function '+name+'\\(')),tail=src.slice(start),end=tail.slice(1).search(/\n(?:async )?function /);assert(start>=0);return end<0?tail:tail.slice(0,end+1)}
(async()=>{const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();await db.exec('create table guilds(id uuid primary key)');let messages=[],mode='ok',checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};const ctx=vm.createContext({Date,process:{env:{GMAIL_USER:'sender@example.com',GMAIL_APP_PASSWORD:'mock'}},clean:v=>String(v||'').trim(),isUuid:v=>/^[a-f0-9-]{36}$/.test(v),requirePlatformMasterCode:v=>{if(v!=='test')throw Object.assign(Error('Denied'),{statusCode:403});},query:(q,p)=>db.query(q,p),nodemailer:{createTransport:()=>({sendMail:async m=>{messages.push(m);if(mode!=='ok')throw Object.assign(Error('secret smtp detail'),{code:mode});return {accepted:[m.to],rejected:[]};}})}});
vm.runInContext(['ensureSupportTicketSchema','ensureSupportReplySchema','normalizeSupportReply','getPlatformSupportReplies','sendPlatformSupportReply'].map(fn).join('\n'),ctx);await ctx.ensureSupportReplySchema();const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
await db.query("insert into platform_support_tickets(id,contact_name,contact_email,subject,message,internal_note) values($1,'Test','player@example.com','Test','Original','PRIVATE'),($2,'Discord','','Only discord','Original','PRIVATE')",[id(1),id(2)]);
const data={masterCode:'test',id:id(1),requestId:id(10),subject:'Re: Test',message:'Hallo, hier ist die Antwort.'};
async function rejected(data,code){await assert.rejects(()=>ctx.sendPlatformSupportReply({body:data}),e=>e.statusCode===code);checks++;}
await rejected({...data,masterCode:'guild-code'},403);await rejected({...data,subject:'header\r\nbcc: another@example.com'},400);await rejected({...data,message:''},400);await rejected({...data,message:'a'.repeat(10001)},400);await rejected({...data,id:id(99)},404);await rejected({...data,id:id(2)},400);eq(messages.length,0);
let first=await ctx.sendPlatformSupportReply({body:{...data,to:'attacker@example.com',recipient:'attacker@example.com'}});eq(first.reply.status,'sent');eq(messages[0].to,'player@example.com');eq(messages[0].replyTo,'sender@example.com');eq(messages[0].text,data.message);eq(JSON.stringify(messages[0]).includes('PRIVATE'),false);
await ctx.sendPlatformSupportReply({body:data});eq(messages.length,1);await rejected({...data,message:'different'},409);
await Promise.all([ctx.sendPlatformSupportReply({body:{...data,requestId:id(11)}}),ctx.sendPlatformSupportReply({body:{...data,requestId:id(11)}})]);eq(messages.length,2);
mode='EAUTH';let fail=await ctx.sendPlatformSupportReply({body:{...data,requestId:id(12)}});eq(fail.reply.status,'failed');eq(fail.reply.error.includes('secret'),false);await ctx.sendPlatformSupportReply({body:{...data,requestId:id(12)}});eq(messages.length,3);
mode='ETIMEDOUT';let unknown=await ctx.sendPlatformSupportReply({body:{...data,requestId:id(13)}});eq(unknown.reply.status,'unknown');await ctx.sendPlatformSupportReply({body:{...data,requestId:id(13)}});eq(messages.length,4);
await assert.rejects(()=>ctx.getPlatformSupportReplies({body:{id:id(1),masterCode:'bad'}}),e=>e.statusCode===403);checks++;
let history=await ctx.getPlatformSupportReplies({body:{id:id(1),masterCode:'test'}});eq(history.replies.length,4);eq(history.recipient,'player@example.com');eq(history.sender,'sender@example.com');eq(JSON.stringify(history).includes('PRIVATE'),false);
await db.query("update platform_support_replies set status='sending',created_at=now()-interval '10 minutes' where id=$1",[id(13)]);history=await ctx.getPlatformSupportReplies({body:{id:id(1),masterCode:'test'}});eq(history.replies.find(r=>r.id===id(13)).status,'unknown');
eq((await db.query('select status,internal_note from platform_support_tickets where id=$1',[id(1)])).rows[0].status,'new');
for(const file of ['admin.html','lichtloot-api/public/admin.html','lichtloot-api/src/admin.html']){for(const match of fs.readFileSync(path.join(__dirname,'../..',file),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);checks++;}
await db.close();console.log(checks+' checks passed: real isolated SQL, mock SMTP; no email sent.');})().catch(e=>{console.error(e);process.exit(1)});
