const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');const root=path.resolve(__dirname,'../..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');function fn(s,n){const start=s.search(new RegExp('(?:async )?function '+n+'\\('));assert(start>=0,n);const t=s.slice(start),end=t.indexOf('\n}\n');return t.slice(0,end+2)};
(async()=>{let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};const helper=await import('data:text/javascript;base64,'+Buffer.from(read('lichtloot-api/src/support-attachments.js')).toString('base64'));const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
eq(helper.validateSupportScreenshot(png),png);eq(helper.validateSupportScreenshot(''),'');for(const bad of ['data:image/svg+xml;base64,PHN2Zz4=','data:image/png;base64,YWJjZA==',png+'=', 'x'.repeat(7*1024*1024)]){assert.throws(()=>helper.validateSupportScreenshot(bad),e=>e.statusCode===400);checks++}
eq(helper.supportPageUrl('https://lichtloot.de/start.html?leadPin=SECRET&guild=foo#secret'),'https://lichtloot.de/start.html');eq(helper.supportPageUrl('javascript:alert(1)'),'');
const src=read('lichtloot-api/src/server.js');let args;
const ctx=vm.createContext({...helper,supportNotices:{ensure:async()=>{},queueDMs:async()=>{}},ensureSupportTicketSchema:async()=>{},sendSupportNotification:async()=>{},requireGuild:async()=>({id:'g',slug:'test',name:'Testgilde'}),resolveGuildSlug:s=>s,defaultGuildSlug:'lichtloot',clean:v=>String(v||'').trim(),query:async(sql,p)=>{args=p;return {rows:[{id:'t',screenshot_data:p[10],screenshot_name:p[11]}]}}});vm.runInContext(fn(src,'normalizeSupportTicketRow')+'\n'+fn(src,'submitSupportTicket'),ctx);
const body={contactName:'Test',contactEmail:'test@example.com',subject:'Fehlermeldung',message:'Die Seite lädt nicht.',pageUrl:'https://lichtloot.de/start.html?masterCode=SECRET',screenshotData:png,screenshotName:'fehler.png'};
let result=await ctx.submitSupportTicket({body});eq(args[9],'https://lichtloot.de/start.html');eq(args[10],png);eq(result.ticket.hasScreenshot,true);eq(result.ticket.screenshotData,undefined);
await assert.rejects(()=>ctx.submitSupportTicket({body:{...body,contactEmail:'',contactDiscord:''}}),e=>e.statusCode===400);checks++;
// The screenshot retrieval route requires platform authorization before touching the DB.
const start=src.indexOf('    if (action === "platformGetSupportScreenshot") {'),end=src.indexOf('    if (action === "platformUpdateSupportTicket") {',start);let queried=false;const route=vm.createContext({action:'platformGetSupportScreenshot',req:{body:{masterCode:'bad',id:'id'},query:{}},enforceSecurityRateLimit(){},requirePlatformMasterCode(){throw Error('unauthorized')},query:async()=>{queried=true}});vm.runInContext('async function run(){'+src.slice(start,end)+'}',route);await assert.rejects(()=>route.run(),/unauthorized/);eq(queried,false);
for(const file of ['index.html','start.html','admin.html'])for(const m of read(file).matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/\bsrc\s*=|application\/ld\+json|application\/json/.test(m[1]))continue;new vm.Script(m[2],{filename:file});checks++;}
new vm.Script(read('support-form.js'));checks++;
for(const file of ['index.html','start.html']){const s=read(file);assert(s.includes('data-guild-support'));assert(s.includes('/support-form.js'));checks+=2;}
console.log(`${checks} assertions and syntax checks passed; no live tickets sent.`)
})().catch(e=>{console.error(e);process.exit(1)});
