const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'../src/server.js'),'utf8');function fn(name){const start=src.search(new RegExp('(?:async )?function '+name+'\\(')),tail=src.slice(start),end=tail.slice(1).search(/\n(?:async )?function /);assert(start>=0);return end<0?tail:tail.slice(0,end+1)}
(async()=>{const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++};await db.exec('create table guilds(id uuid primary key)');const ctx=vm.createContext({supportInbox:{ensure:async()=>{await ctx.ensureSupportTicketSchema();await db.exec("create table if not exists platform_support_incoming(ticket_id uuid,read_at timestamptz)");}},query:(sql,args)=>db.query(sql,args),clean:v=>String(v||'').trim(),isUuid:v=>/^[a-f0-9-]{36}$/i.test(v),requirePlatformMasterCode:v=>{if(v!=='fixture'){const e=Error('Unauthorized');e.statusCode=403;throw e}}});vm.runInContext(['ensureSupportTicketSchema','normalizeSupportTicketRow','getPlatformSupportTickets','updatePlatformSupportTicket'].map(fn).join('\n'),ctx);await ctx.ensureSupportTicketSchema();await ctx.ensureSupportTicketSchema();checks++;
const id='00000000-0000-0000-0000-000000000001';await db.query("insert into platform_support_tickets(id,guild_slug,guild_name,contact_name,subject,message,internal_note,updated_at) values($1,'nachtloot','Nachtwächter','Test','Fehler','Nachricht','Nur intern','2026-09-06T12:00:00.123456Z')",[id]);let r=await ctx.getPlatformSupportTickets({query:{masterCode:'fixture'}});eq(r.total,1);eq(r.tickets[0].internalNote,'Nur intern');eq(r.tickets[0].screenshotData,undefined);eq(ctx.normalizeSupportTicketRow({internal_note:'secret'}).internalNote,undefined);
let ticket=(await ctx.updatePlatformSupportTicket({body:{masterCode:'fixture',id,status:'in_progress',internalNote:'Prüfung läuft',expectedUpdatedAt:r.tickets[0].updatedAt}})).ticket;eq(ticket.status,'in_progress');eq(ticket.internalNote,'Prüfung läuft');eq(ticket.resolvedAt,'');
await assert.rejects(()=>ctx.updatePlatformSupportTicket({body:{masterCode:'fixture',id,status:'resolved',expectedUpdatedAt:r.tickets[0].updatedAt}}),e=>e.statusCode===409);checks++;
ticket=(await ctx.updatePlatformSupportTicket({body:{masterCode:'fixture',id,status:'resolved',expectedUpdatedAt:ticket.updatedAt}})).ticket;assert(ticket.resolvedAt);checks++;eq(ticket.internalNote,'Prüfung läuft');const resolvedAt=ticket.resolvedAt;
ticket=(await ctx.updatePlatformSupportTicket({body:{masterCode:'fixture',id,status:'resolved',internalNote:'Erledigt',expectedUpdatedAt:ticket.updatedAt}})).ticket;eq(ticket.resolvedAt,resolvedAt);
ticket=(await ctx.updatePlatformSupportTicket({body:{masterCode:'fixture',id,status:'new',internalNote:'',expectedUpdatedAt:ticket.updatedAt}})).ticket;eq(ticket.resolvedAt,'');eq(ticket.internalNote,'');
for(const body of [{masterCode:'bad',id,status:'new'},{masterCode:'fixture',id,status:'invalid'},{masterCode:'fixture',id,status:'new',internalNote:'x'.repeat(6001)},{masterCode:'fixture',id,status:'new',expectedUpdatedAt:'bad'}]){await assert.rejects(()=>ctx.updatePlatformSupportTicket({body}),e=>[400,403].includes(e.statusCode));checks++;}
await assert.rejects(()=>ctx.getPlatformSupportTickets({query:{masterCode:'bad'}}),e=>e.statusCode===403);checks++;
await db.exec("insert into platform_support_tickets(guild_slug,guild_name,contact_name,subject,message,category,status) select 'lichtloot','Lichtbringer','Test','Meldung '||n,'Test','raid','in_progress' from generate_series(1,105) n");r=await ctx.getPlatformSupportTickets({query:{masterCode:'fixture',status:'in_progress',guildFilter:'lichtloot',category:'raid'}});eq(r.total,105);eq(r.tickets.length,100);eq(r.hasMore,true);eq(r.groups.reduce((s,g)=>s+Number(g.count),0),106);let page2=await ctx.getPlatformSupportTickets({query:{masterCode:'fixture',status:'in_progress',guildFilter:'lichtloot',category:'raid',offset:100}});eq(page2.tickets.length,5);eq(page2.hasMore,false);eq(new Set([...r.tickets,...page2.tickets].map(t=>t.id)).size,105);
eq((await ctx.getPlatformSupportTickets({query:{masterCode:'fixture',guildFilter:"' OR 1=1 --"}})).total,0);
for(const p of ['admin.html','lichtloot-api/public/admin.html','lichtloot-api/src/admin.html']){for(const m of fs.readFileSync(path.join(__dirname,'../..',p),'utf8').matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/\bsrc\s*=|application\/ld\+json|application\/json/.test(m[1]))continue;new vm.Script(m[2]);checks++;}}
await db.close();console.log(checks+' SQL, authorization, concurrency and syntax checks passed; isolated PostgreSQL only.');})().catch(e=>{console.error(e);process.exit(1)});
