const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),vm=require('vm');
(async()=>{const {createSupportInbox,relatedSupportMessages,supportMessageText}=await import('../src/support-inbox.js');const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();let checks=0,read=true,fullReads=[],metadata=[];const eq=(a,b)=>{assert.deepEqual(a,b);checks++};const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`,anchor={id:id(2),gmail_message_id:'own',gmail_thread_id:'thread'};
function m(gid,from,refs,text='Antwort',mime='text/plain'){return {id:gid,threadId:'thread',internalDate:'1788700000000',labelIds:['INBOX'],payload:{mimeType:mime,headers:[{name:'From',value:from},{name:'Message-ID',value:`<${gid}@example.com>`},{name:'In-Reply-To',value:refs},{name:'Subject',value:'Re: Login'}],body:{data:Buffer.from(text).toString('base64url')}}};}
const one=m('one','Spieler <player@example.com>',`<support-reply-${id(2)}@lichtloot.de>`),two=m('two','player@example.com','<one@example.com>'),unrelated=m('private','player@example.com','<unrelated@example.com>'),spoof=m('spoof','stranger@example.com',`<support-reply-${id(2)}@lichtloot.de>`),sent={...m('own','support@example.com','','Own'),labelIds:['SENT']};
metadata=[two,unrelated,spoof,sent,one];eq(relatedSupportMessages(metadata,[anchor],'player@example.com','support@example.com').map(x=>x.id),['one','two']);
eq(supportMessageText(m('html','','','<script>alert(1)</script><p>Hallo &amp; danke</p><img src=x>','text/html').payload),'Hallo & danke');eq(supportMessageText({mimeType:'text/plain',filename:'secret.txt',body:{data:Buffer.from('attachment secret').toString('base64url')}}).includes('attachment secret'),false);
await db.exec(`create table platform_support_tickets(id uuid primary key,contact_email text,status text,updated_at timestamptz default now(),resolved_at timestamptz);create table platform_support_replies(id uuid primary key,ticket_id uuid,status text,gmail_message_id text,gmail_thread_id text)`);
await db.query("insert into platform_support_tickets values($1,'player@example.com','resolved',now(),now()),($2,'other@example.com','new',now(),null)",[id(1),id(9)]);await db.query("insert into platform_support_replies values($1,$2,'sent','own','thread')",[id(2),id(1)]);
const api={status:async()=>({readConnected:read,email:'support@example.com'}),supportThreadMetadata:async()=>metadata,supportMessage:async id=>{fullReads.push(id);return metadata.find(x=>x.id===id);}};const service=createSupportInbox({query:(q,p)=>db.query(q,p),gmailApi:api,ensureReplySchema:async()=>{}});
read=false;eq((await service.syncTicket(id(1))).skipped,true);eq(fullReads.length,0);read=true;eq((await service.syncTicket(id(1))).imported,2);eq(fullReads.sort(),['one','two']);let h=await service.history(id(1));eq(h.incoming.length,2);eq(h.incoming.every(x=>x.unread),true);eq((await db.query('select status from platform_support_tickets where id=$1',[id(1)])).rows[0].status,'in_progress');
eq((await service.syncTicket(id(1))).imported,0);eq(fullReads.length,2);await service.markRead(id(9),['one']);eq((await service.history(id(1))).incoming.every(x=>x.unread),true);await service.markRead(id(1),['one']);eq((await service.history(id(1))).incoming.find(x=>x.id==='one').unread,false);eq((await service.history(id(1))).incoming.find(x=>x.id==='two').unread,true);
await db.query("update platform_support_tickets set status='resolved',resolved_at=now() where id=$1",[id(1)]);await service.syncTicket(id(1));eq((await db.query('select status from platform_support_tickets where id=$1',[id(1)])).rows[0].status,'resolved');
metadata.push(m('three','player@example.com','<two@example.com>'));eq((await service.syncTicket(id(1))).imported,1);eq((await service.history(id(1))).incoming.length,3);eq((await service.latest(id(1))).thread_id,'thread');
api.supportThreadMetadata=async()=>{throw Error('private error')};eq(!!(await service.syncTicket(id(1))).error,true);eq((await service.history(id(1))).incoming.length,3);eq((await service.history(id(1))).sync.error.includes('private'),false);
for(const f of ['admin.html','lichtloot-api/public/admin.html','lichtloot-api/src/admin.html']){for(const m of fs.readFileSync(path.join(__dirname,'../..',f),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);checks++;}
await db.close();console.log(checks+' support inbox checks passed; all Gmail reads simulated.');})().catch(e=>{console.error(e);process.exit(1)});
